nginx:
  image: plm-nginx
  ports:
    - "80:80"
    - "443:443"
messagequeue:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
plm:
  image: buggleinc/webplm:latest
  volumes:
    - "~/.plm:/root/.plm"
    - "~/webPLM/logs/:/app/webplm-dist/logs"
  ports:
    - "9443:9443"
  environment:
    PLM_FACEBOOK_OAUTH_REDIRECT_URL:
    PLM_GITHUB_OAUTH_REDIRECT_URL:
    GITHUB_CLIENT_ID:
    GITHUB_CLIENT_SECRET:
    PLM_GOOGLE_OAUTH_REDIRECT_URL:
    PLM_PLMACCOUNTS_OAUTH_REDIRECT_URL:
    PLMACCOUNTS_CLIENT_ID:
    PLMACCOUNTS_CLIENT_SECRET:
    GITHUB_ACCESS_TOKEN:
    PLM_EXECUTION_MODE:
  links:
    - accounts
    - profiles
    - messagequeue:messageq
accounts:
  image: plm-accounts
  ports:
    - "9000:3000"
  links:
    - db
profiles:
  image: plm-profiles
  ports:
    - "8080:3000"
  links:
    - db
db:
  image: mongo
  volumes:
    - "~/mongodb/data:/data/db"
  ports: 
    - "27017:27017"
