version: '2'
services:
  messagequeue:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  plm:
    image: buggleinc/webplm:2.0.0-rc6
    volumes:
      - "~/.plm:/root/.plm"
      - "~/webPLM/logs:/app/webplm-dist/logs"
    ports:
      - "9000:9000"
      - "9443:9443"
    links:
      - messagequeue
    environment:
      GITHUB_ACCESS_TOKEN:
      PLM_EXECUTION_MODE: "TRIBUNAL"
      MESSAGEQUEUE_ADDR: "messagequeue"
      MESSAGEQUEUE_PORT: "5672"
  judge:
    image: buggleinc/plm-judge:2.0.0-rc3
    links:
      - messagequeue
    environment:
      MESSAGEQUEUE_ADDR: "messagequeue"
      MESSAGEQUEUE_PORT: "5672"
    restart: "always"
