version: '2'
services:
  nginx:
    image: buggleinc/plm-nginx:1.1.0-dev
    ports:
      - "80:80"
    links:
      - plm
      - messagequeue
  messagequeue:
    image: buggleinc/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
  plm:
    image: buggleinc/webplm:2.1.1
    volumes:
      - "~/.plm:/root/.plm"
      - "~/webPLM/logs:/app/webplm-dist/logs"
    ports:
      - "9000:9000"
      - "9443:9443"
    links:
      - messagequeue
    environment:
      GITHUB_ACCESS_TOKEN:
      PLM_EXECUTION_MODE: "TRIBUNAL"
      MESSAGEQUEUE_ADDR: "messagequeue"
      MESSAGEQUEUE_PORT: "5672"
  judge:
    image: matthieunicolas/plm-judge:2.1.1
    links:
      - messagequeue
    environment:
      MESSAGEQUEUE_ADDR: "messagequeue"
      MESSAGEQUEUE_PORT: "5672"
    restart: "always"
