version: '2'
services:
  judge:
    image: matthieunicolas/plm-judge:2.1.1
    environment:
      MESSAGEQUEUE_ADDR:
      MESSAGEQUEUE_PORT:
    restart: "always"
    mem_limit: "4G"
    command: ["java", "-Xmx1024m", "-Xms1024m", "-javaagent:/app/judge/plumbr/plumbr.jar", "-Dpython.cachedir=/app/judge/cachedir", "-jar", "PLM-judge.jar"]
    volumes:
      - "~/webPLM/plumbr:/app/judge/plumbr"
      - "~/webPLM/cachedir:/app/judge/cachedir"
