version: '2'
services:
  judge:
    image: buggleinc/plm-judge:2.0.2
    environment:
      MESSAGEQUEUE_ADDR:
      MESSAGEQUEUE_PORT:
    restart: "always"
    mem_limit: "4G"
    command: ["java", "-jar", "PLM-judge.jar", "-Xmx1024m", "-Xms1024m"]
