version: '2'
services:
  judge:
    image: buggleinc/plm-judge:2.0-rc3
    environment:
      MESSAGEQUEUE_ADDR:
      MESSAGEQUEUE_PORT:
    restart: "always"
    mem_limit: "512M"
    memswap_limit: "768M"
