version: '2'
services:
  nginx:
    image: buggleinc/plm-nginx:1.1.0-tncy
    volumes:
      - "~/webPLM/ssl:/etc/nginx/ssl"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    cpu_shares: 1024
  messagequeue:
    image: buggleinc/rabbitmq
    ports:
      - "5672:5672"
      - "15674:15674"
    restart: "always"
    cpu_shares: 1024
  plm:
    image: buggleinc/webplm:2.1.1
    command: ["-J-Xmx8g", "-J-Xms8g", "-J-javaagent:newrelic/newrelic.jar", "-J-javaagent:/app/webplm/plumbr/plumbr.jar"]
    volumes:
      - "~/webPLM/PLM-data:/root/.plm"
      - "~/webPLM/logs:/app/webplm/logs"
      - "~/webPLM/newrelic:/app/webplm/newrelic"
      - "~/webPLM/plumbr:/app/webplm/plumbr"
    ports:
      - "9443:9443"
    environment:
      GITHUB_ACCESS_TOKEN:
      PLM_EXECUTION_MODE: "TRIBUNAL"
      MESSAGEQUEUE_ADDR: "messagequeue"
      MESSAGEQUEUE_PORT: "5672"
      PLMACCOUNTS_ACCESS_TOKEN_URL:
      PLMACCOUNTS_API_URL:
      PLMACCOUNTS_AUTHORIZATION_ENDPOINT_URL:
      PLM_OAUTH_REDIRECT_URL:
      PLM_FACEBOOK_OAUTH_REDIRECT_URL:
      PLM_PLMACCOUNTS_OAUTH_REDIRECT_URL:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      PLMACCOUNTS_CLIENT_ID:
      PLMACCOUNTS_CLIENT_SECRET:
    links:
      - accounts
      - profiles
      - messagequeue
    restart: "always"
    cpu_shares: 2048
  accounts:
    image: buggleinc/plm-accounts:2.0.0-rc2
    ports:
      - "9000:8443"
    environment:
      DB_ADDR: "db"
      SESSION_SECRET:
      MAILER_FROM:
      MAILER_SERVICE_PROVIDER:
      MAILER_EMAIL_ID:
      MAILER_PASSWORD:
    links:
      - db
    restart: "always"
    cpu_shares: 512
  profiles:
    image: buggleinc/plm-profiles:2.0.0-rc4
    ports:
      - "8080:8443"
    environment:
      DB_ADDR: "db"
      SESSION_SECRET:
      API_ID:
      API_SECRET:
    links:
      - db
    restart: "always"
    cpu_shares: 512
  db:
    image: mongo
    volumes:
      - "~/mongodb/data:/data/db"
    ports:
      - "27017:27017"
    restart: "always"
    cpu_shares: 1024
